Add digital ocaen
qdrant/hybrid-cloud-examples pull request #1
Opened 2024-02-26 10:40 UTC by vzholudev

2024-02-26 13:42 UTC, bashofmann commented on digitalocean/terraform/backend.tf
> +  backend "s3" {
The examples should also easily be runnable by external customers. Therefor remove the S3 backend here. We should only use the default file backend for the state.

2024-02-26 13:43 UTC, bashofmann commented on digitalocean/terraform/main.tf
> +module "test-cluster" {
I don't think a module is necessary here, I think I'd prefer a flat structure here.

2024-02-26 13:44 UTC, bashofmann commented on digitalocean/terraform/modules/cluster-setup/README.md
> +This module is for baisic setup VPC and k8s cluster in DigitalOcean project.
```suggestion
This module is for a basic VPC and k8s cluster setup in a DigitalOcean project. 
```

2024-02-26 13:45 UTC, bashofmann commented on digitalocean/README.md
> +# Qdrant Hybrid Cloud Example for DigitalOcean
This readme needs some basic info on how to use this.

2024-02-29 16:34 UTC, bashofmann requested changes
Sorry for the delay, I was out-of-office for a couple days. The following points need to be addressed:

* The vpc `ip_range` needs to be configurable through a variable
* The provider configuration is missing, something like
```
variable "do_token" {}

provider "digitalocean" {
  token = var.do_token
}
```
* Add `*.tfvars` to `.gitignore`
* Add a `terraform.tfvars.example` file, see https://github.com/rancher/quickstart/blob/master/rancher/do/terraform.tfvars.example
* Auto generate this tfvars example file and the docs, see https://github.com/rancher/quickstart/blob/master/Makefile#L15-L21
* Write the generated kubeconfig (https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/kubernetes_cluster#raw_config) to a ignored file for easy usage

2024-03-02 12:31 UTC, vzholudev commented
@bashofmann please take a look one more time

2024-03-04 09:50 UTC, bashofmann approved these changes

2024-03-04 10:02 UTC, merged